name = "test"
version = "0.1.0"
defaultTargets = ["test"]

[[require]]
name = "llmlean"
git = "https://github.com/fbundle/llmlean.git"
rev = "main"

[[lean_lib]]
name = "type_theory"

[[lean_lib]]
name = "tactic"

[[lean_exe]]
name = "test"
root = "Main"
